version: '3'
services:
  mysql:
      image: "mysql:5.5"
      environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: propel
        MYSQL_USER: propel
        MYSQL_PASSWORD: propel
      ports:
        - "8989:3306"
      volumes:
        - "./data/db/mysql:/var/lib/mysql"
        - "./mysql_schemas:/docker-entrypoint-initdb.d"
  propel_bash:
    image: "php56-alpine-bash:v0.1.0"
    build: "./php5.6.37-alpine-bash/"
    volumes:
      - "../:/usr/src/propel"
    working_dir: "/usr/src/propel"
  php_56_composer:
    image: "php56-alpine-composer:v0.1.0"
    build: "./php5.6.37-alpine-composer"
    volumes:
      - "../:/app"
    command: ["install"]
